### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [MegDuck/qemu-tui#1]
Hi, what license is applied to this project?

**Comment by MegDuck** [comment]
There's no license, use it however and wherever you want

**Comment by LifeCANvs** [comment]
> There's no license, use it however and wherever you want

Thanks! Perhaps for clarity to everyone who may be interested in this project of yours, you could thus add the "Unlicense license" to it?

**Comment by MegDuck** [comment]
aight, done! thanks for suggestion
